version: '3'
services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile.dev

    ports:
      - "4200:4200"
    volumes:
      - /app/node_modules
      - /d/Projects/DockerLearning/AngularDemo/angular-docker-demo:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - /d/Projects/DockerLearning/AngularDemo/angular-docker-demo:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm","run","test"]


